spring.application.name=ConsultoriaDeImagem

spring.datasource.url=jdbc:postgresql://localhost:5432/consulta_db
spring.datasource.username=consulta_user
spring.datasource.password=consulta_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.google.genai.api-key=${GENAI_API_KEY}
spring.ai.google.genai.model=gemini-2.5-flash

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
